# Generated by Django 4.2.2 on 2023-06-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='gameDay',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.RemoveField(
            model_name='team',
            name='skillLevel',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='team',
            name='userTeam',
        ),
        migrations.AddField(
            model_name='team',
            name='game_day',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='skill_level',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='first_app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='first_app.team')),
            ],
        ),
    ]
